version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongo:27017/mir-flashcard?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mongo:
    image: mongo:6
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mir-flashcard
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
